### PR TITLE
addButtonItem method

### PR DESCRIPTION
**Pull request by gfontenot**
Added an addButtonItem method so that you can still create the UIActionSheet or UIAlertView dynamically with arrays.

### CODE REVIEW

**Comment by jivadevoe** [comment]
Hey, thanks for the patch. Can you shoot me some example code for how this method would be used?

**Comment by gfontenot** [comment]
Sure. I'm using this to build an ActionSheet of Twitter clients installed on the device. So I create a dict of the possible URL schemes and client names, and do the following:

```
if ([[UIApplication sharedApplication] canOpenURL:urlScheme]) {
    RIButtonItem *twitterButton = [RIButtonItem item];
    twitterButton.label = [NSString stringWithFormat:@"Open in %@", twitterClient];
    twitterButton.action = ^{
        [[UIApplication sharedApplication] openURL:[NSURL URLWithString:[NSString stringWithFormat:@"%@%@",[twitterDict objectForKey:twitterClient] , twitterUser]]];
    };
    [installedTwitterClients addObject:twitterButton];
}
```

Then, once I've created an array of objects, I cycle through to add the buttons to the ActionSheet:

```
UIActionSheet *twitterSheet = [[UIActionSheet alloc] initWithTitle:sheetTitle cancelButtonItem:nil destructiveButtonItem:nil otherButtonItems:nil];

for (RIButtonItem *item in installedTwitterClients) {
    [twitterSheet addButtonItem:item];
}

[twitterSheet addButtonItem:cancelItem];
[twitterSheet setCancelButtonIndex:[installedTwitterClients count]];

[twitterSheet showInView:self.view];
[installedTwitterClients release];
[twitterSheet release];
```

AFAIK, there is no other way to build a `UIActionSheet` with an array, as opposed to individual button items. My initial thought was to just add a method to build the sheet with an Array, but this seemed simpler.

**Comment by jivadevoe** [comment]
Cool. I like it.  I'll try to review the code and get it merged this weekend.

**Comment by jivadevoe** [comment]
If you can add a note to the docs WRT how to use this, I'd appreciate it, and will merge that too.  Thanks!

**Pull request merged**
