### PR TITLE
To reduce risk of conflict renamed action to actionBlock

### PR DESCRIPTION
**Pull request by p-l**
To address the [comment on commit `e2c23df0708c7afb6a824d26d433a447c89dda30`](https://github.com/jivadevoe/UIAlertView-Blocks/commit/e2c23df0708c7afb6a824d26d433a447c89dda30#commitcomment-3440433) by @MrNickBarker I propose renaming `action` to `actionBlock` in `RIButtonItem`. 

I'm also including an example projet to make testing UIAlertView-Blocks easier.

### CODE REVIEW

**Comment by jivadevoe** [comment]
What's the rationale behind changing action to actionBlock?  Can you explain the conflict in question?

**Comment by p-l** [comment]
Since type `id` is used when declaring a `newItem` ([RIButtonItem.m line 29](https://github.com/jivadevoe/UIAlertView-Blocks/blob/master/RIButtonItem.m#L29)). The compiler (from XCode 4.6.3 in my case) does not know which `setAction:` to call and assumes it's `UIBarButtonItem`. 

Two options:
1. We can be explicit about the type and change `id` to `RIButtonItem*`
2. Rename the action to resolve the "conflict" with the method name.

I choose option 2 since I found actionBlock more explicit. But I can easily go with option 1 if you prefer. Your repo, your rules.

**Comment by jivadevoe** [comment]
Your option 1 was fixed by someone else previously and was just waiting for a merge from me, so I went ahead and merged it. I opted for that fix instead of changing the selector name because I figured that there were already a number of people who were using the existing API and who would not want to change their code.

I hope you don't mind.  That said, thank you very much for the pull request it is appreciated.

**Comment by jivadevoe** [comment]
The other pull request was #25 FYI.

**Pull request closed without merging**
